export const SIGNIN = 'AUTH/SIGNIN';
export const SIGNUP = 'AUTH/SIGNUP';
export const LOGOUT = 'AUTH/LOGOUT';
export const LOGGED = 'AUTH/LOGGED';

export const FOLLOW = 'DATA/FOLLOW';
export const FOLLOWS = 'DATA/FOLLOWS';
export const VACATIONS = 'DATA/VACATIONS';
export const VACATIONS_CREATE = 'DATA/VACATIONS_CREATE';
export const VACATIONS_DELETE = 'DATA/VACATIONS_DELETE';
export const VACATIONS_UPDATE = 'DATA/VACATIONS_UPDATE';

export const PENDING = 'STATUS/PENDING';
export const SUCCESS = 'STATUS/SUCCESS';
export const FAILURE = 'STATUS/FAILURE';

export const SIGNIN_SIGNAL = 'STATUS/VACATIONS_SELECT_SIGNAL';
export const SIGNUP_SIGNAL = 'STATUS/VACATIONS_CREATE_SIGNAL';
export const LOGOUT_SIGNAL = 'STATUS/LOGOUT_SIGNAL';
export const LOGGED_SIGNAL = 'STATUS/LOGGED_SIGNAL';

export const VACATIONS_SIGNAL = 'STATUS/VACATIONS_SIGNAL';

export const FOLLOW_SIGNAL = 'STATUS/FOLLOW_SIGNAL';
export const UNFOLLOW_SIGNAL = 'STATUS/UNFOLLOW_SIGNAL';

export const VACATIONS_SELECT_SIGNAL = 'STATUS/VACATIONS_SELECT_SIGNAL';
export const VACATIONS_CREATE_SIGNAL = 'STATUS/VACATIONS_CREATE_SIGNAL';
export const VACATIONS_DELETE_SIGNAL = 'STATUS/VACATIONS_DELETE_SIGNAL';
export const VACATIONS_UPDATE_SIGNAL = 'STATUS/VACATIONS_UPDATE_SIGNAL';

export const MODAL_SIGNAL = 'STATUS/MODAL_SIGNAL';
export const ACTION_SIGNAL = 'STATUS/ACTION_SIGNAL';
export const AUTH_SIGNAL = 'STATUS/AUTH_SIGNAL';
export const LOCATION_SIGNAL = 'STATUS/LOCATION_SIGNAL';

export const ACTION_INSERT = 'STATUS/ACTION_INSERT';
export const ACTION_UPDATE = 'STATUS/ACTION_UPDATE';

export const AUTH_SIGNIN = 'STATUS/AUTH_SIGNIN';
export const AUTH_SIGNUP = 'STATUS/AUTH_SIGNUP';

export const INPUT_CLEAR = 'INPUT/INPUT_CLEAR';
export const INPUT_UPDATE = 'INPUT/INPUT_UPDATE';
export const INPUT_INSERT_FIELDS = 'INPUT/INPUT_INSERT_FIELDS';
export const INPUT_UPDATE_FIELDS = 'INPUT/INPUT_UPDATE_FIELDS';
export const INPUT_SIGNUP_FIELDS = 'INPUT/INPUT_SIGNUP_FIELDS';
export const INPUT_SIGNIN_FIELDS = 'INPUT/INPUT_SIGNIN_FIELDS';

export const INPUT_VALIDATION_FIRSTNAME = 'STATUS/INPUT_VALIDATION_FIRSTNAME';
export const INPUT_VALIDATION_LASTNAME = 'STATUS/INPUT_VALIDATION_LASTNAME';
export const INPUT_VALIDATION_USERNAME = 'STATUS/INPUT_VALIDATION_USERNAME';

export const INPUT_VACATION_PASSWORD = 'STATUS/INPUT_VACATION_PASSWORD';

export const INPUT_VACATION_VALIDATION = 'STATUS/INPUT_VACATION_VALIDATION';
export const INPUT_SIGNUP_VALIDATION = 'STATUS/INPUT_SIGNUP_VALIDATION';
